### ISSUE TITLE
RPM not being published

### ISSUE THREAD

**Issue by PascalBoeschoten** [alisw/ali-bot#504]
Hello, 

Configuration v1.2.0 RPM has not been published yet, which was built yesterday (job build-any-ib/6559).
Could there be an issue with the RPM publisher?

Cheers,
Pascal

**Comment by dberzano** [comment]
We currently deploy Monitoring and Configuration-Benchmark (and all of their dependencies). This was intended, you should rebuild Monitoring if you want the new version of Configuration to be deployed as well. Otherwise, if you want the sole Configuration package to be published, we can add it to the list (you can open a PR or ask @brinick to do that).

**Comment by PascalBoeschoten** [comment]
Clear, thanks!
